

cloud: # aws
  bucket_name: "askly-bucket"   # S3 bucket holding the documents
  clean_prefix: "clean/"        # output: cleaned JSON documents

embedding:
  dense_model_name: "llama-text-embed-v2"   
  sparse_model_name: "pinecone-sparse-english-v0" 
  dimension: 1024
  metric: "cosine"

vector_db: #pinecone
  namespace: "askly-namespace"
  index_name: "askly-index"
  batch_size: 96